CB-Group-6-Project-1/travel-board

README.md
- Made MVP section a bullet list
- Added Motivation section
=> Make MVP bullet list; Add Motivation section

assets/css/style.css, index.html
I added base HTML page cards for upcoming, active and past vacations and added special IDs for the different sections.
close #8
=> i added the basic HTML structure of the vacation planner page

index.html
resolved #7 
Made a simple grid
=> initial html for city details section

assets/css/style.css, assets/js/script.js, index.html
=> Search destination

assets/js/script.js, index.html
=> added on click for popular destinations

assets/js/script.js, index.html
resolved #7 
Updated city details section with carousel. Will add cards later when I have time to checkout more materialize documentation.
=> added carousel and supporting js functionality

assets/css/style.css, assets/js/script.js, index.html
- added common class and ids to all page sections
- added functions placeholders for city details parts
=> Added function to load city details

assets/js/script.js, index.html
=> 15 destination section details

assets/css/style.css, assets/js/script.js, index.html
- added MVP placeholder cards for the data.
- display the weather.
- get the city name from the loadCityFromPopular.
- added data-name attribute to the popular images in order to get the city.
- added the function loadCityWeather().
=> Weather destination

assets/css/style.css, assets/js/script.js, index.html
Pulls first 3 shopping results and displays on shopping card.
=> added function for getting shopping data from mapbox

assets/js/script.js
Resolved #16 
added todo data to final card, 
changed name of restaurant function to loadPoiData, 
called loadPoiData function in correct place, 
added comments.
=> added function for getting todo data from mapbox, cleaned up

assets/js/script.js
I added the ability to retrieve Flickr URLs and images 
close #20
=> commented out tutor code and got image URLs

assets/css/style.css, assets/js/script.js, index.html
- added general map
- populate the images on js without carousel (MVP) static random images for now.
- added some CSS classes
=> Map destination

assets/js/script.js
- added the **point** on the map given the city
=> Added the market for the city given the center

assets/css/style.css, assets/js/script.js, index.html
- carousel fixed.
-added map directions.
added maps new views and options like full-screen view.
- added the functionality to go back to the home page.
- added a global variable to get the active city when we click the plan vacation.
- action plan vacation.
closes #24
=> Plan vacation

assets/js/script.js
- changed the zoom number to 5 
closes #57
=> changed the zoom number to 5

assets/css/style.css, assets/js/script.js, index.html
resolved #62 
#9 
Updated plan vacation section with info cards, minimal style, and date picker.
=> 62 plan vacation section update

assets/css/style.css, assets/js/script.js, index.html
- Validate city on search
- Reuse city data when loading info
- Refactor POI code to handle when there is less data than expected by UI
=> 61 data validation

assets/css/style.css, assets/js/script.js, index.html
=> 26 vacation notes

assets/css/style.css, assets/js/script.js, index.html
- change the text for the API flicker
- populate restaurants, shopping & todo
- changing jquery cdn UI
- get the data values
- creating a date object with the from and to dates
closes #25
=> Select start-end dates

assets/css/style.css, assets/js/script.js, index.html
resolved #28 
Will add function to remove list item this evening.
=> 28 add/remove todos

assets/js/script.js
changed the API we were retrieving for the pictures to a stock images site which in turn improved predictability for our pictures! 
close #70
=> improved predictability with the pictures by changing the API

assets/css/style.css, assets/js/script.js
=> 28 remove todos

assets/css/style.css, assets/js/script.js, index.html
- fixing cards and HTML structure
- fixed clear activity function
- added a guest with a chip
- added a guest info
closes #27
=> Guest add-remove 

assets/css/style.css, assets/js/script.js, index.html
closes #29 
- added the functionality to get the notes, guests, and activities and object plan created
- added the save trip action
=> Save vacation plan

assets/css/style.css, assets/js/script.js, index.html
closes #30 
- created the active vacation with a few plan properties
- added vacation plans populate on js
- added vacation plans to the localStorage
- added local storage functionality
=> Load active vacation

assets/js/script.js, index.html
closes #32 
closes #33 
closes #34 
- **Group** travel plans by **date**
- **Refactor** _save trip_ function
=> Group plans

assets/js/script.js
- added the validation to vacation plan
- changed API Url
=> Added the validation to vacation plan

assets/css/style.css, index.html
=> 81 improve ui design

assets/js/script.js, index.html
- added button to delete the travel
- delete travel plans function
closes #35
=> 35 delete trip

assets/js/script.js, index.html
added trim to guest info
validated guest phone number to accept 10 digit number in the following formats:
xxxxxxxxxx
xxx xxx xxxx
xxx.xxx.xxxx
xxx-xxx-xxxx
more testing and validation needed.
=> 90 testing

assets/css/style.css, assets/js/script.js, index.html
- UI city details change.
- responsive city details
=> Improve ui design

assets/css/style.css, index.html
resolved #94 
Responsive fixes,
Added .custom-cards style
=> 94 plan vacation ui

assets/js/script.js, index.html
- Add modal error on plan vacation validations.
- Added validation to the search button with modals, added validation to the place_name response from the API to avoid display city details page.
- Added missing validation to activities, guest name and API city name
- Added modal to all errors
=> Add modals

assets/css/style.css
=> added a fresh font for the page

README.md, assets/css/style.css, assets/js/script.js, index.html
- make responsive focus mobile device last version
=> Project review

assets/js/city.js, assets/js/core.js
- Documented all **js** _files_
=> Added documentation to the js files

assets/css/style.css
- Fix images hover on small screens
=> Fix images hover on small screens

assets/css/style.css, index.html
- responsive plan vacation page
=> User experience improve

assets/css/style.css, assets/js/city.js, assets/js/script.js, index.html
- **Disable** _map_ _zoom_ _scroll_
- **Fix** travel plan info _cards size_
- **Added** _buttons_ to go _back home_
=> Fix errors

README.md
- update readme with **missing** _user stories_ and _acceptance criteria_
- added **description** to _js files_
=> Readme last update
